version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'thursday'
      time: '02:00'
    open-pull-requests-limit: 10
    groups:
      # group name
      playwright:
        patterns: ["*playwright*"]

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
