name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Get checksum of svanill.html on S3
      id: checksum-s3-svanill
      run: |
        aws s3api head-object --bucket svanill.com --key svanill.html > head_svanill
        echo "##[set-output name=md5;]$(jq -r '.ETag | fromjson' < head_svanill)"

    - name: Get checksum of local svanill.html
      id: checksum-local-svanill
      run: |
        echo "##[set-output name=md5;]$(md5sum svanill.html | cut -d' ' -f1)"

    - name: Copy files to S3 with the AWS CLI
      if: steps.checksum-s3-svanill.outputs.md5 != steps.checksum-local-svanill.outputs.md5
      run: |
        aws s3 cp svanill.html s3://svanill.com/svanill.html

    - name: Sync htdocs to S3
      run: |
        aws s3 sync --size-only htdocs/ s3://svanill.com/